import type { Metadata } from 'next'
import 'keen-slider/keen-slider.min.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body>{children}</body>
    </html>
  )
}
